version: 1.0.{build}
image: Visual Studio 2017
clone_depth: 1
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

build_script:
- cmd: >-
    nuget.exe restore

    
    msbuild Core\Get.the.solution.UWP.XAML.csproj  /property:Configuration=Debug


    msbuild Core\Get.the.solution.UWP.XAML.csproj  /property:Configuration=Debug /property:Platform=x64


    msbuild Core\Get.the.solution.UWP.XAML.csproj  /property:Configuration=Debug /property:Platform=x86


    msbuild Core\Get.the.solution.UWP.XAML.csproj  /property:Configuration=Debug /property:Platform=ARM


    msbuild Core\Get.the.solution.UWP.XAML.csproj  /property:Configuration=Release /property:Platform=x64


    msbuild Core\Get.the.solution.UWP.XAML.csproj  /property:Configuration=Release /property:Platform=x86


    msbuild Core\Get.the.solution.UWP.XAML.csproj  /property:Configuration=Release /property:Platform=ARM



# scripts to run after build
after_build:
  - ps: .\pack.ps1

# scripts to run after tests
after_test:

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
# https://ci.appveyor.com/tools/encrypt
# https://www.appveyor.com/docs/deployment/nuget/
deploy:
  cmd: >-
    publish.cmd oTV9gUFj6oUVmuG7731mwbuMvXQ1yGNDGGxQkEJg4ZNiU6GnHpGO8EcCbUBOpBxA

