# check https://dzone.com/articles/uwp-class-library-to-multi-architecture-nuget-pack
version: 1.0.{build}
image: Visual Studio 2017
clone_depth: 1
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

build_script:
- cmd: >-
    nuget.exe restore

    
    msbuild Core\Get.the.solution.UWP.XAML.csproj  /property:Configuration=Debug


    msbuild Core\Get.the.solution.UWP.XAML.csproj  /property:Configuration=Debug /property:Platform=x64


    msbuild Core\Get.the.solution.UWP.XAML.csproj  /property:Configuration=Debug /property:Platform=x86


    msbuild Core\Get.the.solution.UWP.XAML.csproj  /property:Configuration=Debug /property:Platform=ARM


    msbuild Core\Get.the.solution.UWP.XAML.csproj  /property:Configuration=Release /property:Platform=x64


    msbuild Core\Get.the.solution.UWP.XAML.csproj  /property:Configuration=Release /property:Platform=x86


    msbuild Core\Get.the.solution.UWP.XAML.csproj  /property:Configuration=Release /property:Platform=ARM

    mkdir Core\bin\Release

    copy /Y Core\bin\x86\Release\Get.the.solution.UWP.XAML.dll Core\bin\Release

    copy /Y Core\bin\x86\Release\Get.the.solution.UWP.XAML.pri Core\bin\Release



    "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"


    corflags.exe /32bitreq- Core\bin\Release\Get.the.solution.UWP.XAML.dll


    exit




# scripts to run after build
after_build:
  - ps: .\pack.ps1


# scripts to run after tests
# after_test:

artifacts:

  - path: '*.nupkg'

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
# https://ci.appveyor.com/tools/encrypt
# https://www.appveyor.com/docs/deployment/nuget/
deploy:
  provider: NuGet
  api_key:
    secure: BvkUK7Qnhf+XPxgdQZ23yXI/uc6rS6s9Eu2Nx36ZxLzohK7guwSdjOHTyj15Jn9f
  artifact: /.*\.nupkg/