<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <UseUwp>true</UseUwp>
    <RootNamespace>App1</RootNamespace>
    <AssemblyName>App1</AssemblyName>
    <DefaultLanguage>en-US</DefaultLanguage>
    <Platforms>x86;x64;arm64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Properties\AssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Get.the.solution.UWP.XAML.csproj" />
  </ItemGroup>

</Project>